name: Deploy to Prod Kubernetes Cluster
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    environment: prod
    env:
      HARBOR_URL: ${{ secrets.HARBOR_URL }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HAS_SECRETS: ${{ secrets.HAS_SECRETS }} # BOOLEAN TO KNOW IF THE SERVICE NEEDS SECRET ENVS
      K8S_SECRETS: ${{ secrets.K8S_SECRETS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
      - name: Install tools for deployment
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          skaffold: '1.38.0'
      - name: Docker login Harbor
        run: docker login $HARBOR_URL -u=$HARBOR_USERNAME -p=$HARBOR_PASSWORD 
      - name: Add secrets to k8s 
        run: |
          if [ $HAS_SECRETS == 'true' ]
          then
            touch secret-envs.txt | echo $K8S_SECRETS | base64 --decode > ./secret-envs.txt
            cat ./secret-envs.txt
            echo "    files:" | tee -a k8s/prod/kustomization.yaml
            while IFS= read -r secret
            do
            SECRET_NAME=$(echo $secret | cut -d '=' -f 1)
            SECRET_VALUE=$(echo $secret | cut -d '=' -f 2)
            echo $SECRET_VALUE > k8s/prod/private/$SECRET_NAME.env
            printf %s $(< k8s/prod/private/$SECRET_NAME.env) > k8s/prod/private/$SECRET_NAME.env
            echo "      - $SECRET_NAME=private/$SECRET_NAME.env" | tee -a k8s/prod/kustomization.yaml
            done < secret-envs.txt 
          fi
      - name: verify Kustomization
        run: cat k8s/prod/kustomization.yaml
      - name: Run skaffold prod
        run: skaffold run -p prod
