name: Deploy to Dev Kubernetes Cluster
on:
  pull_request:
    types: [ closed ]
    branches: [ dev ]
jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    environment: dev
    env:
      HARBOR_URL: ${{ secrets.HARBOR_URL }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HAS_SECRETS: ${{ secrets.HAS_SECRETS }} # BOOLEAN TO KNOW IF THE SERVICE NEEDS SECRET ENVS
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
      - name: Install tools for deployment
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          skaffold: '1.38.0'
      - name: Docker login Harbor
        run: docker login $HARBOR_URL -u=$HARBOR_USERNAME -p=$HARBOR_PASSWORD 
      - name: Add secrets to k8s 
        run: |
          if [ $HAS_SECRETS == 'true' ]
          then
            echo "    files:" | tee -a k8s/dev/kustomization.yaml
            while IFS= read -r secret
            do
            SECRET_NAME=$(echo $secret)
            echo "secrets.$SECRET_NAME"
            SECRET="secrets.$SECRET_NAME"
            SECRET_VALUE=secrets.$SECRET_NAME
            echo "Secret value:: $SECRET_VALUE"
            echo $SECRET_VALUE > k8s/dev/private/$SECRET_NAME.env
            printf %s $(< k8s/dev/private/$SECRET_NAME.env) > k8s/dev/private/$SECRET_NAME.env
            echo "      - $SECRET_NAME=private/$SECRET_NAME.env" | tee -a k8s/dev/kustomization.yaml
            done < secrets_list.txt 
          fi
      - name: verify Kustomization
        run: cat k8s/dev/kustomization.yaml
      - name: Run skaffold
        run: skaffold run -p dev
